# Generated by Django 4.0.5 on 2022-08-12 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('p2p', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wallet name')),
                ('address', models.CharField(editable=False, max_length=250, verbose_name='Wallet Address')),
                ('public_key', models.CharField(editable=False, max_length=250, verbose_name='Wallet public key')),
                ('private_key', models.CharField(editable=False, max_length=250, verbose_name='Wallet private key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bitcoin_wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='EthereumWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wallet name')),
                ('address', models.CharField(editable=False, max_length=250, verbose_name='Wallet Address')),
                ('public_key', models.CharField(editable=False, max_length=250, verbose_name='Wallet public key')),
                ('private_key', models.CharField(editable=False, max_length=250, verbose_name='Wallet private key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ethereum_wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ETHTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_address', models.CharField(max_length=250, verbose_name='Transaction recipient address')),
                ('hash', models.CharField(blank=True, max_length=250, null=True, verbose_name='Transaction hash')),
                ('confirmed', models.BooleanField(default=False, max_length=50, verbose_name='Transaction confirmation status')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Transaction amount in wei')),
                ('fees', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Transaction fees in wei')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='p2p.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.ethereumwallet', verbose_name='Transaction wallet')),
            ],
        ),
        migrations.CreateModel(
            name='BTCTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_address', models.CharField(max_length=250, verbose_name='Transaction recipient address')),
                ('hash', models.CharField(blank=True, max_length=250, null=True, verbose_name='Transaction hash')),
                ('confirmed', models.BooleanField(default=False, max_length=50, verbose_name='Transaction confirmation status')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Transaction amount in Satoshi')),
                ('fees', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Transaction fees in Satoshi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='p2p.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.bitcoinwallet', verbose_name='Transaction wallet')),
            ],
        ),
    ]
