# Generated by Django 4.0.5 on 2022-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_btctransaction_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btctransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ethtransaction',
            name='order',
        ),
        migrations.AddField(
            model_name='ethereumwallet',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='Wallet balance in wei'),
        ),
    ]
