# Generated by Django 4.0.5 on 2022-09-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_ethereumwallet_usdt_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereumwallet',
            name='vica_balance',
            field=models.BigIntegerField(default=0, verbose_name='Wallet vica balance'),
        ),
    ]
