# Generated by Django 4.0.5 on 2022-09-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_ethereumwallet_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumwallet',
            name='balance',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=23, verbose_name='Wallet ether balance'),
        ),
    ]
