# Generated by Django 4.0.5 on 2022-09-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_ethereumwallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoinwallet',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12, verbose_name='Wallet btc balance'),
        ),
    ]
