# Generated by Django 4.0.5 on 2022-10-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_bitcoinwallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btctransaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12, verbose_name='Transaction amount in btc'),
        ),
        migrations.AlterField(
            model_name='ethtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=33, verbose_name='Transaction amount'),
        ),
    ]
