# Generated by Django 4.0.5 on 2022-11-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_btctransaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btctransaction',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='ethtransaction',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='btctransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Transaction confirmation status'),
        ),
        migrations.AddField(
            model_name='ethtransaction',
            name='currency',
            field=models.CharField(blank=True, choices=[('ETHER', 'Ethereum'), ('VICA', 'Vica Token'), ('USDT', 'Tether (USDT)')], max_length=50, null=True, verbose_name='Transaction currency'),
        ),
        migrations.AddField(
            model_name='ethtransaction',
            name='from_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Transaction recipient address'),
        ),
        migrations.AddField(
            model_name='ethtransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Transaction confirmation status'),
        ),
        migrations.AlterField(
            model_name='ethtransaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.ethereumwallet', verbose_name='Transaction wallet'),
        ),
    ]
