# Generated by Django 4.0.5 on 2022-11-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_remove_btctransaction_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethtransaction',
            name='timestamp',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Transaction fees in wei'),
        ),
    ]
