# Generated by Django 4.0.5 on 2022-11-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_ethtransaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='btctransaction',
            name='from_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Transaction sender address'),
        ),
        migrations.AddField(
            model_name='btctransaction',
            name='inputs',
            field=models.JSONField(default=dict, null=True, verbose_name='Transaction inputs'),
        ),
        migrations.AddField(
            model_name='btctransaction',
            name='outputs',
            field=models.JSONField(default=dict, null=True, verbose_name='Transaction outputs'),
        ),
        migrations.AddField(
            model_name='btctransaction',
            name='timestamp',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Transaction timestamp'),
        ),
        migrations.AlterField(
            model_name='btctransaction',
            name='recipient_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Transaction recipient address'),
        ),
        migrations.AlterField(
            model_name='ethtransaction',
            name='timestamp',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Transaction timestamp'),
        ),
    ]
