# Generated by Django 4.0.5 on 2022-11-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=33, verbose_name='Staked amount'),
        ),
        migrations.AlterField(
            model_name='arbitragetransaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('PENDING', 'Withdraw Pending'), ('COMPLETED', 'Withdraw Completed')], default='CREATED', max_length=20, verbose_name='Status of the staking transaction'),
        ),
    ]
