# Generated by Django 4.0.5 on 2022-08-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'Sell')], max_length=20, verbose_name='What you would like to do? (Buy or Sell)')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETHER', 'Ethereum'), ('VICA', 'Vica Token'), ('USDT', 'Tether (USDT)')], max_length=20, verbose_name='Currency (BTC, ETHER, USDT, VICA)')),
                ('amount', models.BigIntegerField(verbose_name='Amount to reach')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price for one currency')),
                ('label', models.CharField(blank=True, max_length=200, null=True, verbose_name='Offer label')),
                ('terms', models.CharField(blank=True, max_length=250, null=True, verbose_name='Offer terms')),
                ('instructions', models.CharField(blank=True, max_length=250, null=True, verbose_name='Offer instructions')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended')], default='DRAFT', max_length=20, verbose_name='Offer Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BT', 'Bank Transfers'), ('CP', 'Cash Payment'), ('DC', 'Digital Currencies'), ('GC', 'Gift Cards')], max_length=100, verbose_name='Payment method type ')),
                ('name', models.CharField(max_length=100, verbose_name='Payment method name (BTC, Western union, ABC bank..)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, db_index=True, help_text='Unique order number', max_length=250, null=True, unique=True, verbose_name='Order Number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price for one currency')),
                ('amount_sent', models.BigIntegerField(blank=True, null=True, verbose_name='Amount sent to the Offer owner')),
                ('amount_received', models.BigIntegerField(blank=True, null=True, verbose_name='Amount received to the user')),
                ('fees', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='VICA Foundation fees in USD')),
                ('confirmed_by_user', models.BooleanField(default=False, verbose_name='User confirmation')),
                ('confirmed_by_owner', models.BooleanField(default=False, verbose_name='Offer owner confirmation')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='Order Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2p.offer', verbose_name='Offer')),
            ],
        ),
    ]
