# Generated by Django 4.0.5 on 2022-08-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Order Status'),
        ),
    ]
