# Generated by Django 4.0.5 on 2022-09-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0004_offer_time_limit_offer_trade_limit_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETHER', 'Ethereum'), ('VICA', 'Vica Token'), ('USDT', 'Tether (USDT)')], max_length=20, verbose_name='Currency to buy/sell (BTC, ETHER, USDT, VICA)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Offer instructions'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='terms',
            field=models.TextField(blank=True, null=True, verbose_name='Offer terms'),
        ),
    ]
