# Generated by Django 4.0.5 on 2022-09-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0007_alter_offer_amount_alter_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='p2p.offer', verbose_name='Offer'),
        ),
    ]
