# Generated by Django 4.0.5 on 2022-09-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0009_userpaymentmethod_order_user_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.BooleanField(default=True, verbose_name='User review')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='User comment')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='p2p.order', verbose_name='Order reviewed')),
            ],
        ),
    ]
