# Generated by Django 4.0.5 on 2022-09-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Payment method name (BTC, Western union, ABC bank..)'),
        ),
    ]
