# Generated by Django 4.0.5 on 2022-10-28 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p2p', '0013_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Dispute resolving status'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='message',
            field=models.TextField(verbose_name='Dispute message content'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='p2p.order', verbose_name='Order of the dispute'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dispute sender'),
        ),
    ]
