# Generated by Django 4.0.5 on 2022-11-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0014_dispute_is_resolved_alter_dispute_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2p.paymentmethod', verbose_name='Payment method to pay with if offer is buy or be paid with if offer is sell'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VICA Foundation fees'),
        ),
    ]
