# Generated by Django 4.0.5 on 2022-11-25 10:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='', upload_to=users.models.photo_upload_path),
        ),
    ]
